version: '3'
services:
  nanomind_frontend:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/NanoMindFrontend
      - /NanoMindFrontend/node_modules
    ports:
      # rails app
      - "3000:3000"
      # webpack dev server
      - "3035:3035"
      # Ports required for debugging
      - "1234:1234"
      - "26166:26168"
